[View in Colaboratory](https://colab.research.google.com/github/vineykhera/ML-practice/blob/master/Neural_Networks_notes.ipynb)

# Pickle 

Pickle - like feather, but pickle works for only python, feather files we can give to others to use but pickle files can only be used by python
It can take a Python Object, dump it out onto disk, share, load it back later
Feather is optimal for pandas df rather than Pcikle, pickle will take more time.

Python gzip - to load/open it up

```
def load_mnist(filename):
    return pickle.load(gzip.open(filename, 'rb'), encoding='latin-1')
```

# Tuples

Tuple of Tuples, it gives back tuple of training, validation, test data

something assigned to _, you are giving it away

For Jupyther notebook underscore _ means - last cell we calculate, is always available in underscore

underscore in pytorch as suffix means "in-place"


Destructuring - tuple of tuples
```
((x, y), (x_valid, y_valid), _) = load_mnist(path+FILENAME)
```

# Naming

```
math    comp sc       deep learning 

vector = 1d array =  rank 1 tensor
matrix = 2d array =  rank 2 tensor             
                     r 3 tensor  
rows/cols = dimension1/2 = axis 0, axis 1

Confusing :
  
image person --cols by rows, 
everyone else (DL, CS)-- rows by cols

```

# Normalize

*   RF depends on sort order of independent variables, mean, std dev doesnt matter
*   in DL, we need to normalize data, subtract mean and divide by std deviation, do same in train, test and validation set
*   scaling by pixel - for trees scaling isnt needed, as you are branching by numbers, no timeline, DL algos need scaling


**change a flatted image(r1 tuple) to image **
```

In [38]:

x_valid.shape

Out[38]:

(10000, 784)


x_imgs = np.reshape(x_valid, (-1,28,28)); x_imgs.shape

```

-1 used instead of 10k, its used to find smallest or largest number, as we shouldnt need to always put biggest number, its useful at lot
of places, when you are taking subset



opencv lib reads images and orders channels blue green red 
everyone else do red green blue

how do we transform it back:

**practice - reshape/slicing/reordering dimensions**





```
In [41]:

y_valid.shape

Out[41]:

(10000,)             -------------> Tuple with rank 1 tensor, needs a comma

It's the digit 3! And that's stored in the y value:
In [42]:

y_valid[0]

Out[42]:

3

We can look at part of an image:
In [19]:

x_imgs[0,10:15,10:15]            -----------------------> example of slicing into a tensor, with 0 slicing into 1st axis, single number, so it will reduce rank of tensor by 1 i.e. from 3d arr to 2d arr 

Out[19]:

array([[-0.42452, -0.42452, -0.42452, -0.42452,  0.17294],
       [-0.42452, -0.42452, -0.42452,  0.78312,  2.43567],
       [-0.42452, -0.27197,  1.20261,  2.77889,  2.80432],
       [-0.42452,  1.76194,  2.80432,  2.80432,  1.73651],
       [-0.42452,  2.20685,  2.80432,  2.80432,  0.40176]], dtype=float32)


x_imgs[0:1,10:15,10:15]  

```

imshow - can take numpy array n draw a picture



# Loss functions

* RF - information gain - rmse

* NN - loss function ( definition) = value lower if this is better

* cross entropy - binary, cross 

* binary - NLLLoss = negative log likelihood loss

* 10 predictions per image

![alt text](https://i.imgur.com/YE5Pw9E.png)

![alt text](https://i.imgur.com/Gh9xJjA.png)

---



---



# **argmax** = returns index of value 

* turns probability back to index, returns index of highest value

* Pytorch uses word Crit (criterion) for loss 

* similar to logistic regression

# Neural Networks

 * NN = Linear followed by non linear, universal approximation theorem
 * Micheal Nielsen - NN can approximate any function
 * Pytorch module can be NN or a layer in NN
 *  
```
  our class if it inherits a existing class, it needs to call super().__init__()
  need to initialize weight and bias
  
    weight bias
  y = ax + bm
  weight --- a
  bias ---- b
 ``` 
  get_weights - random number, weights - increase/decrease size exponentially, 
  
  so we need to  make sure weitghts are correct so that mean of the input doesnt change, if we use normal distributed numbers and divide by number of rows, then weights turn out to be of right scale
  
  Gradient explosion 
  
  
  forward method - special method in pytorch, gets called when layer is calculated, prev layer is passed to it
  
  pytorch view = reshape
  
  soft max --- output --- e^output ---- e^out/sum of all e^out
  
  its like a probability
  
  **Softmax is a great activation function**
  
  sum of softmax = 1
  
  
**nn.parameter** 

* which things to update when we do SGD
  
**  forward **
  
1  Flatten it, view = reshape

2  apply linear func, matrix multiplication

3  apply softmax

![alt text](https://i.imgur.com/IVfnkGS.png)


**go through Pytorch tutorial - matmul, view, create tensor**




# Good blogs students did - Lesson 9 beginning

https://www.youtube.com/watch?v=PGC0UxakTvM&feature=youtu.be

* RF - visualization of bagging using colors
* RF - hyperper param selection library - parfit
* Parfit - how to make SGD classifier using parfit
* Kernel - Devesh Maheshwari - keras model for Beginners - Iceberg calssifier 
  challange, iceberg vs ship, radar scattering
* Complete RF summary - using waterfall chart
 
* RF - why to use log of continuous variables 

  https://www.google.com/search?ei=ZQqjWpecCsOkjwPqv7igBQ&q=why+use+log+of+continuous+variables+in+regression&oq=why+use+log+of+continuous+var&gs_l=psy-ab.3.0.33i22i29i30k1.15047.27296.0.29725.31.31.0.0.0.0.187.3877.0j27.27.0....0...1.1.64.psy-ab..4.27.3869...0j35i39k1j0i67k1j0i131k1j0i3k1j0i22i30k1j33i21k1.0.coeu9b63pqE

* why to blog Rachel article

# SGD

* nn.Module is a pytorch class
* contruct object - constructor 
* call super construct
* malmul --> @ (pyhton 3 multiplication)

try finding blog about :(ashley)
* structured data analysis using NN

**nn.parameter** 

* optimize it, 
* which things to update when we do SGD
* calls it using net2.parameters()

pytorch data loader - trn_dl
Generators - mini batches - please give me another one

iterators and generators are close

# Python function 
 iter, next
 
  xmb - x mini batch - tensor
  vxmb = variable(xmb) - variable containing tensor  - wrapping tensor into variable, so that later we can use it to 
  indicate that it needs differentiation
  
  free automatic differentiation 

# NN
  * add hidden linear layer
  
  * Relu - Rectifier Liner unit - change all negative to 0, 
            added after liner layer, activation function, non linear layer

# Activation Functions

* For final layer:
   * softmax (for binary classification)
   * sigmoid (for)
* For Hidden Layers:
  * RELU
  * Leaky RELU
  * elu
  
* Pytorch argmax is max, max returns actual max and its index  

# Broadcasting

**element wise operations operator sign is *, Matrix maltiplication operator sign is @**



* in NumPy and T (pytorch) - faster than for loop, as C for loop is 10 k faster than python, plus it can use multiple cores which muliplies speed
  + if we use cuda then it will multiply even more 

![alt text](https://puu.sh/zKqIZ/4608cc9d6d.png)

so try to avoid loops and use elemet wise operations

**2 ways to do this:**

c.shape (3,)  - array
m = 3x3 matrix

c + m ?? 

1) np.expand_dims(c,1)  - changes to 3x 1

2) add None - easier than expand_dims - index into tensor with special index none
   none creates new axis inthat loc of length 1

   c[None].shape ---> adds new axis in start of len 1, 1x3
   c[:,None].shape --> adds new axis at end of len 1, 3x1
   c[None,:,None] ---> want to do both 1x3x1
   

  broadcast_to function - to see (how array will be converted) in a broadcast operation
  
  np.broadcast_to(C,(3,3))
  
  np.broadcast_to(C,m.shape)

  np.broadcast_to(C[:,None],m.shape)



**Rules** : https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

    they are equal, or
    one of them is 1

If these conditions are not met, a ValueError: frames are not aligned exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

Arrays do not need to have the same number of dimensions. For example, if you have a 256x256x3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible:


In [0]:
import numpy as np
c = np.array([1,2,3])
c.shape

import numpy as np
c = np.array([1,2,3])
c.shape

In [6]:
c[None]

array([[1, 2, 3]])

In [8]:
c[:,None].shape

(3, 1)

In [11]:
c[None].shape

(1, 3)

In [10]:
c[:,None]

array([[1],
       [2],
       [3]])

In [16]:
c[None] * c[:,None]

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [13]:
 b = c[:,None] * c[None]; b

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [0]:
x = np.arange(4)
>>> xx = x.reshape(4,1)
>>> y = np.ones(5)
>>> z = np.ones((3,4))

In [0]:
??np.arange

```
InDependent var and dependent variables 
x              and   y


Regularization in NN -- by adding weight decay or Drop out

Adding to many variables in NN helps

```



# Naive Bayes

 r = p/q
 
 rx + b
 
 
 -> 0 -> 1
 
# Logistic regrssion = wx
 
        now changing it to  r (x.w)
 
 
** (w + wadj) * r **
 
 regularization wants weights to be 0 (default assumption), but we dont want that so adding Wadj (= 0.4)

 
 

# zip - imp function to practice

# Learn Pandas timeSeries  api/functions

# Embeddding 
 is a weight matrix we can multiply by 1 hot encoding, its a computational shortcut - but mathematically same

# Key differences b/W SGD and Tree models

Analyzing

Ordinals as categorical in Trees, no need for normalization
fast.ai max 1 hot encoding level is 50

Interpretting RF

Shuffling columns can be done in NN as well, 

Partial dependence curve can also be done in NN


